---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yh.
--- DateTime: 2022/1/28 15:51
---



while true do
    print('----测试Lua成功');
    touchDown(1, 100 , 100);
    sleep(200)
    touchUp(1 , 100, 100);
    sleep(3000)
end
